language: php

php:
  - '5.4'

before_install:
- composer require phpunit/phpunit:4.8.* satooshi/php-coveralls:dev-master
- composer install --dev

script:
  - mkdir -p tests/logs
  - ./vendor/bin/phpunit --coverage-clover tests/logs/clover.xml tests

after_script:
  - php vendor/bin/coveralls -v
