language: php

php:
  - '5.4'

service:
- mysql

before_install:
- composer require phpunit/phpunit:4.8.* satooshi/php-coveralls:0.6.*
- composer install
- mysql -e 'DROP DATABASE IF EXISTS vortech;'
- mysql -e 'CREATE DATABASE IF NOT EXISTS vortech;'
- mysql -u root --default-character-set=utf8 vortech < setup/create_db.sql

script:
  - mkdir -p tests/logs
  - ./vendor/bin/phpunit --coverage-clover tests/logs/clover.xml tests

after_script:
  - php vendor/bin/coveralls -v
