language: php

php:
  - '7.1'

service:
- mysql

before_install:
- composer require phpunit/phpunit:6.2.3 satooshi/php-coveralls:1.0.1
- composer install
- mysql -e 'DROP DATABASE IF EXISTS vortech;'
- mysql -e 'CREATE DATABASE IF NOT EXISTS vortech;'
- mysql -u root --default-character-set=utf8 vortech < setup/create_db.sql

script:
  - mkdir -p tests/logs
  - ./vendor/bin/phpunit --whitelist tests --coverage-clover tests/logs/clover.xml tests

after_script:
  - php vendor/bin/coveralls -v
